### ISSUE TITLE
find not defined variables

### ISSUE THREAD

**Issue by chalesguo** [bckenstler/dsb17-walkthrough#1]
In [188]:
for prop in properties:
    if prop.area * spacing[1]*spacing[2] > 30 and prop.eccentricity < 0.99:    ------------>spacing
        valid_label.add(prop.label)
In [452]: np.unique(measure.label(bw_test))    ----->bw-test

**Comment by bckenstler** [comment]
Thanks for pointing that out. Should be fixed.
